#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hsr.Campus.Droid.Resource", IsApplication=true)]

namespace Hsr.Campus.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::Hsr.Campus.Droid.Resource.String.library_name;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::Hsr.Campus.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::Hsr.Campus.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::Hsr.Campus.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::Hsr.Campus.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::Hsr.Campus.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::Hsr.Campus.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::Hsr.Campus.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::Hsr.Campus.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::Hsr.Campus.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::Hsr.Campus.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::Hsr.Campus.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::Hsr.Campus.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::Hsr.Campus.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::Hsr.Campus.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::Hsr.Campus.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Hsr.Campus.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::Hsr.Campus.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::Hsr.Campus.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::Hsr.Campus.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Hsr.Campus.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::Hsr.Campus.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080003
			public const int bar = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int canvas = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int hsr_blue = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int light_grey = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int red = 2131230724;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int widget_margin = 2131296256;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back_hsr = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back_sv_group = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int border_left = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int hsr_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_act_account = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_act_cafeteria = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_act_calendar = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_act_card = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_act_compass = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_act_heart = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_act_info = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_act_network = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_act_news = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_act_not_secure = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_act_panda = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_act_secure = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_act_setup = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_act_sport = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_act_storage = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_action_exams = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_action_refresh = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_action_rotate = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_action_settings = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_action_take_away = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_action_today = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_adunis_exam = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_adunis_timetable = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_io_file = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_io_folder = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_launcher = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_splash = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int mupdf_ic_arrow_left = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int mupdf_ic_arrow_right = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int mupdf_ic_cancel = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int mupdf_ic_search = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int round_box = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int round_box_blue = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int status_hsr = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int text_clickable = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int trans_select = 2130837543;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MvvmCrossTagId = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MvxBindingTagUnique = 2131099649;
			
			// aapt resource value: 0x7f060018
			public const int actors = 2131099672;
			
			// aapt resource value: 0x7f060005
			public const int btn = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int btnDelete = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int content = 2131099652;
			
			// aapt resource value: 0x7f060011
			public const int description = 2131099665;
			
			// aapt resource value: 0x7f06000b
			public const int empty = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int image = 2131099662;
			
			// aapt resource value: 0x7f06001b
			public const int imgSplash = 2131099675;
			
			// aapt resource value: 0x7f060008
			public const int lastUpdated = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int lastUpdatedText = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int lastUpdatedValue = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int layout = 2131099650;
			
			// aapt resource value: 0x7f060010
			public const int lecturers = 2131099664;
			
			// aapt resource value: 0x7f060007
			public const int list = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int loading = 2131099660;
			
			// aapt resource value: 0x7f060016
			public const int menuWebViewPager = 2131099670;
			
			// aapt resource value: 0x7f06001e
			public const int menu_refresh = 2131099678;
			
			// aapt resource value: 0x7f06001c
			public const int menu_settings = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int menu_weekNr = 2131099677;
			
			// aapt resource value: 0x7f060019
			public const int message = 2131099673;
			
			// aapt resource value: 0x7f060014
			public const int more_info = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int overview = 2131099669;
			
			// aapt resource value: 0x7f060012
			public const int rooms = 2131099666;
			
			// aapt resource value: 0x7f06001a
			public const int settingslist = 2131099674;
			
			// aapt resource value: 0x7f060013
			public const int tabViewPagerView = 2131099667;
			
			// aapt resource value: 0x7f06000f
			public const int time = 2131099663;
			
			// aapt resource value: 0x7f060003
			public const int title = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int updating = 2131099661;
			
			// aapt resource value: 0x7f060017
			public const int webView1 = 2131099671;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AccountBalanceView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int AccountViewComplete = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int AccountViewIndex = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int AccountViewInfo = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int AccountViewRenew = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int AdunisView = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int AdunisViewItem = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int CalendarFeedView = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int CalendarFeedViewItem = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int ExamAppointment = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int ExamView = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int ExamViewItem = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int FilerView = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int FilerViewItem = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int HomeView = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int MapView = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int MapViewHome = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int MapViewItem = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int MenuFeedView = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int MenuView = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int MenuWebView = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int NewsFeedView = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int NewsFeedViewItem = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int NewsView = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int SettingsView = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int SettingsViewItem = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int SplashScreen = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int SportsView = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int TimetableAppointment = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int TimetableView = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int TimetableViewItem = 2130968606;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int home = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int timetable = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int updateable = 2131427330;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_launcher_foreground = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_launcher_round = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int AccountBalance = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int AccountSetupVerify = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int ActionCancel = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int ActionDelete = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int ActionOk = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int AddLiveTile = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int AppBarButtonText = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int AppFirstRunMessage = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int AppFirstRunTitle = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int AppVersion = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int AppVersionTitle = 2131165196;
			
			// aapt resource value: 0x7f070064
			public const int ApplicationName = 2131165284;
			
			// aapt resource value: 0x7f07000a
			public const int ApplicationTitle = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int BadgeText = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int BadgeUpdate = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int ConnectionFailed = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int DateTimeRealtiveNow = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int DateTimeRealtiveSeconds = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int DateTimeRelativeDays = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int DateTimeRelativeHours = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int DateTimeRelativeMinutes = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int DayFriday = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int DayMonday = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int DaySaturday = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int DaySunday = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int DayThursday = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int DayTuesday = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int DayWednesday = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int DownloadingError = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int DownloadingFile = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int LastUpdate = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int Loading = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int LoadingEvents = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int LoadingMenus = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int LoadingNetwork = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int LoadingNews = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int LoadingNewsNew = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int LoadingTimetable = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int LocationFormat = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int MapBuilding = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int MapFirstRunMessage = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int MapFirstRunMessageAndroid = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int MapFirstRunTitle = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int MapOverview = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int MessageCredentials = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int MessageCredentialsDelete = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int Modules = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int NewsReadMore = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int NoEntries = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int NoMaps = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int NoMenus = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int NoNetworkList = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int NoTimetable = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int OAuthComplete = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int OAuthError = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int OAuthErrorDenied = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int OAuthIdentity = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int OAuthNextRefresh = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int OAuthPermissions = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int OAuthRemove = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int OAuthRemoveConfirm = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int OAuthRenew = 2131165245;
			
			// aapt resource value: 0x7f07003e
			public const int OAuthSetup = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int OpeningError = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int OpeningFile = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int Password = 2131165249;
			
			// aapt resource value: 0x7f070042
			public const int PivotWeek = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int ResourceFlowDirection = 2131165251;
			
			// aapt resource value: 0x7f070044
			public const int ResourceLanguage = 2131165252;
			
			// aapt resource value: 0x7f070045
			public const int SettingAccountTitle = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int SettingAccountTitleSub = 2131165254;
			
			// aapt resource value: 0x7f070048
			public const int SettingAppInfoSubTitle = 2131165256;
			
			// aapt resource value: 0x7f070047
			public const int SettingAppInfoTitle = 2131165255;
			
			// aapt resource value: 0x7f070049
			public const int SettingCacheTitle = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int SettingCacheTitleSub = 2131165258;
			
			// aapt resource value: 0x7f07004b
			public const int SettingOfficialTitle = 2131165259;
			
			// aapt resource value: 0x7f07004c
			public const int SettingOfficialTitleSub = 2131165260;
			
			// aapt resource value: 0x7f07004e
			public const int SettingStorageTitle = 2131165262;
			
			// aapt resource value: 0x7f07004f
			public const int SettingStorageTitleSub = 2131165263;
			
			// aapt resource value: 0x7f070050
			public const int SettingSuccessCacheClear = 2131165264;
			
			// aapt resource value: 0x7f070051
			public const int SettingTimetableSyncInfo = 2131165265;
			
			// aapt resource value: 0x7f070052
			public const int SettingTimetableSyncInfoSub = 2131165266;
			
			// aapt resource value: 0x7f07004d
			public const int Settings = 2131165261;
			
			// aapt resource value: 0x7f070053
			public const int ThirdPartyLibraries = 2131165267;
			
			// aapt resource value: 0x7f070054
			public const int ThirdPartyLibrariesText = 2131165268;
			
			// aapt resource value: 0x7f070055
			public const int TileBadge = 2131165269;
			
			// aapt resource value: 0x7f070056
			public const int TileCampusMap = 2131165270;
			
			// aapt resource value: 0x7f070057
			public const int TileExams = 2131165271;
			
			// aapt resource value: 0x7f070058
			public const int TileLectureNotes = 2131165272;
			
			// aapt resource value: 0x7f070059
			public const int TileMenu = 2131165273;
			
			// aapt resource value: 0x7f07005a
			public const int TileNews = 2131165274;
			
			// aapt resource value: 0x7f07005b
			public const int TileSetupAccount = 2131165275;
			
			// aapt resource value: 0x7f07005c
			public const int TileSport = 2131165276;
			
			// aapt resource value: 0x7f07005d
			public const int TileTimetable = 2131165277;
			
			// aapt resource value: 0x7f07005e
			public const int UpdateBadgeSaldo = 2131165278;
			
			// aapt resource value: 0x7f07005f
			public const int Updating = 2131165279;
			
			// aapt resource value: 0x7f070060
			public const int Username = 2131165280;
			
			// aapt resource value: 0x7f070061
			public const int Warning = 2131165281;
			
			// aapt resource value: 0x7f070062
			public const int WeekSelect = 2131165282;
			
			// aapt resource value: 0x7f070063
			public const int WeekSelection = 2131165283;
			
			// aapt resource value: 0x7f070065
			public const int account_type_name = 2131165285;
			
			// aapt resource value: 0x7f070000
			public const int library_name = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int AppTheme = 2131361792;
			
			// aapt resource value: 0x7f0a0004
			public const int ButtonHome = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int CenteredActionBarTheme = 2131361797;
			
			// aapt resource value: 0x7f0a0001
			public const int SmallAndLight = 2131361793;
			
			// aapt resource value: 0x7f0a0006
			public const int TabTextStyle = 2131361798;
			
			// aapt resource value: 0x7f0a0002
			public const int Theme_Splash = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int Theme_View = 2131361795;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int authenticator = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int provider_paths = 2131034113;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
