//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsr.Campus.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hsr.Campus.Core.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _NET_Core_Library_License {
            get {
                return ResourceManager.GetString("_NET_Core_Library_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. Please read them. They apply to the software named above, which includes the media on which you received it, if any. The terms also apply to any Microsoft
        ///
        ///·         updates,
        ///·         supplements,
        ///·          Internet-based services, and
        ///·          support services
        ///
        ///for this software, unless other terms accompany those items. If so, those terms apply.
        ///BY USING THE SOFTWARE, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _NET_Library_License {
            get {
                return ResourceManager.GetString("_NET_Library_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _NET_Standard_Library_License {
            get {
                return ResourceManager.GetString("_NET_Standard_Library_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHF {0:00.00}.
        /// </summary>
        public static string AccountBalance {
            get {
                return ResourceManager.GetString("AccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying account.
        /// </summary>
        public static string AccountSetupVerify {
            get {
                return ResourceManager.GetString("AccountSetupVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ActionCancel {
            get {
                return ResourceManager.GetString("ActionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ActionDelete {
            get {
                return ResourceManager.GetString("ActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string ActionDone {
            get {
                return ResourceManager.GetString("ActionDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ActionOk {
            get {
                return ResourceManager.GetString("ActionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add live tile.
        /// </summary>
        public static string AddLiveTile {
            get {
                return ResourceManager.GetString("AddLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app serves as a supplement to the existing systems of the HSR. There is no warranty of accuracy, completeness or availability. The information displayed is not legally valid..
        /// </summary>
        public static string AppFirstRunMessage {
            get {
                return ResourceManager.GetString("AppFirstRunMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string AppFirstRunTitle {
            get {
                return ResourceManager.GetString("AppFirstRunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSR Campus.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operatingsystem {0} is no longer supported. This is the last Update of CampusApp for {0}. Perform a operatingsystem update, so you can use the app correctly..
        /// </summary>
        public static string AppStartSupportExpiredMessage {
            get {
                return ResourceManager.GetString("AppStartSupportExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support expired.
        /// </summary>
        public static string AppStartSupportExpiredTitle {
            get {
                return ResourceManager.GetString("AppStartSupportExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AppVersionTitle {
            get {
                return ResourceManager.GetString("AppVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be connected to the HSR network to update your account. This is not a real-time value display, it may take up to an hour for transactions to be processed..
        /// </summary>
        public static string BadgeText {
            get {
                return ResourceManager.GetString("BadgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be connected to the HSR network to update your account. This is not a real-time value display, it may take up to an hour for transactions to be processed.
        ///
        ///You can also add a live tile with your account balance to your device&apos;s home screen..
        /// </summary>
        public static string BadgeTextWindows {
            get {
                return ResourceManager.GetString("BadgeTextWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated: {0:dd.MM.yyyy H:mm:ss}.
        /// </summary>
        public static string BadgeUpdate {
            get {
                return ResourceManager.GetString("BadgeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve data - please check your connection..
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just a second ago.
        /// </summary>
        public static string DateTimeRealtiveNow {
            get {
                return ResourceManager.GetString("DateTimeRealtiveNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} seconds ago.
        /// </summary>
        public static string DateTimeRealtiveSeconds {
            get {
                return ResourceManager.GetString("DateTimeRealtiveSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:g}.
        /// </summary>
        public static string DateTimeRelativeDays {
            get {
                return ResourceManager.GetString("DateTimeRelativeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} hours ago.
        /// </summary>
        public static string DateTimeRelativeHours {
            get {
                return ResourceManager.GetString("DateTimeRelativeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} minutes ago.
        /// </summary>
        public static string DateTimeRelativeMinutes {
            get {
                return ResourceManager.GetString("DateTimeRelativeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string DayDiv {
            get {
                return ResourceManager.GetString("DayDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fr.
        /// </summary>
        public static string DayFriday {
            get {
                return ResourceManager.GetString("DayFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mo.
        /// </summary>
        public static string DayMonday {
            get {
                return ResourceManager.GetString("DayMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa.
        /// </summary>
        public static string DaySaturday {
            get {
                return ResourceManager.GetString("DaySaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su.
        /// </summary>
        public static string DaySunday {
            get {
                return ResourceManager.GetString("DaySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th.
        /// </summary>
        public static string DayThursday {
            get {
                return ResourceManager.GetString("DayThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu.
        /// </summary>
        public static string DayTuesday {
            get {
                return ResourceManager.GetString("DayTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We.
        /// </summary>
        public static string DayWednesday {
            get {
                return ResourceManager.GetString("DayWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download file: {0}.
        /// </summary>
        public static string DownloadingError {
            get {
                return ResourceManager.GetString("DownloadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file....
        /// </summary>
        public static string DownloadingFile {
            get {
                return ResourceManager.GetString("DownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update:.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading events....
        /// </summary>
        public static string LoadingEvents {
            get {
                return ResourceManager.GetString("LoadingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating menus....
        /// </summary>
        public static string LoadingMenus {
            get {
                return ResourceManager.GetString("LoadingMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading directory....
        /// </summary>
        public static string LoadingNetwork {
            get {
                return ResourceManager.GetString("LoadingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading more posts….
        /// </summary>
        public static string LoadingNews {
            get {
                return ResourceManager.GetString("LoadingNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading new posts….
        /// </summary>
        public static string LoadingNewsNew {
            get {
                return ResourceManager.GetString("LoadingNewsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating timetable....
        /// </summary>
        public static string LoadingTimetable {
            get {
                return ResourceManager.GetString("LoadingTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: .
        /// </summary>
        public static string LocationFormat {
            get {
                return ResourceManager.GetString("LocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building {0}.
        /// </summary>
        public static string MapBuilding {
            get {
                return ResourceManager.GetString("MapBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinch and rotate the map to enlarge the image. Double tap a building to view the floorplans..
        /// </summary>
        public static string MapFirstRunMessage {
            get {
                return ResourceManager.GetString("MapFirstRunMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double tap a building to view the floorplans..
        /// </summary>
        public static string MapFirstRunMessageiOS {
            get {
                return ResourceManager.GetString("MapFirstRunMessageiOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSR Campus Map.
        /// </summary>
        public static string MapFirstRunTitle {
            get {
                return ResourceManager.GetString("MapFirstRunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string MapOverview {
            get {
                return ResourceManager.GetString("MapOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your credentials..
        /// </summary>
        public static string MessageCredentials {
            get {
                return ResourceManager.GetString("MessageCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this account?.
        /// </summary>
        public static string MessageCredentialsDelete {
            get {
                return ResourceManager.GetString("MessageCredentialsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License
        ///
        ///Copyright (c) 2013 Paul Betts, 2017 Alex Rainman
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ModernHttpClient_License {
            get {
                return ResourceManager.GetString("ModernHttpClient_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Public License (MS-PL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you
        ///accept this license. If you do not accept the license, do not use the software.
        ///
        ///1. Definitions
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the
        ///same meaning here as under U.S. copyright law.
        ///A &quot;contribution&quot; is the original software, or any additions or changes to the software.
        ///A &quot;contributor&quot; is any person that distributes its contribution und [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MvvmCross_License {
            get {
                return ResourceManager.GetString("MvvmCross_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read more ».
        /// </summary>
        public static string NewsReadMore {
            get {
                return ResourceManager.GetString("NewsReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2007 James Newton-King
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of
        ///this software and associated documentation files (the &quot;Software&quot;), to deal in
        ///the Software without restriction, including without limitation the rights to
        ///use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
        ///the Software, and to permit persons to whom the Software is furnished to do so,
        ///subject to the following conditions:
        ///
        ///The ab [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Newtonsoft_Json_License {
            get {
                return ResourceManager.GetString("Newtonsoft_Json_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Entries.
        /// </summary>
        public static string NoEntries {
            get {
                return ResourceManager.GetString("NoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No maps available.
        /// </summary>
        public static string NoMaps {
            get {
                return ResourceManager.GetString("NoMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No menus currently available for this location..
        /// </summary>
        public static string NoMenus {
            get {
                return ResourceManager.GetString("NoMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lecture note data available.
        /// </summary>
        public static string NoNetworkList {
            get {
                return ResourceManager.GetString("NoNetworkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No timetable available.
        /// </summary>
        public static string NoTimetable {
            get {
                return ResourceManager.GetString("NoTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!
        ///
        ///This device has been authorized to use the HSR mobile services.
        ///
        ///You can manage your authorized devices on:
        ///https://mobile.hsr.ch/.
        /// </summary>
        public static string OAuthComplete {
            get {
                return ResourceManager.GetString("OAuthComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uhh Ohh! An error occured whilst interacting with the HSR OAuth server. Error response: {0}.
        /// </summary>
        public static string OAuthError {
            get {
                return ResourceManager.GetString("OAuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access has been denied by the OAuth server..
        /// </summary>
        public static string OAuthErrorDenied {
            get {
                return ResourceManager.GetString("OAuthErrorDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication procedur is expired.
        ///If you want to login again, you must first delete your account..
        /// </summary>
        public static string OAuthErrorStateAuthenticated {
            get {
                return ResourceManager.GetString("OAuthErrorStateAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication procedur is expired.
        ///Please try it againg..
        /// </summary>
        public static string OAuthErrorStateUnauthenticated {
            get {
                return ResourceManager.GetString("OAuthErrorStateUnauthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        public static string OAuthIdentity {
            get {
                return ResourceManager.GetString("OAuthIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Refresh (UTC).
        /// </summary>
        public static string OAuthNextRefresh {
            get {
                return ResourceManager.GetString("OAuthNextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth Permissions.
        /// </summary>
        public static string OAuthPermissions {
            get {
                return ResourceManager.GetString("OAuthPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Account.
        /// </summary>
        public static string OAuthRemove {
            get {
                return ResourceManager.GetString("OAuthRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By deleting your account you will also remove any personal HSR data (Timetable, Exam, Badge, Lecture Notes) from this device..
        /// </summary>
        public static string OAuthRemoveConfirm {
            get {
                return ResourceManager.GetString("OAuthRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission for this device has either been revoked or the OAuth token expired before it could be refreshed. Please reauthenticate this device..
        /// </summary>
        public static string OAuthRenew {
            get {
                return ResourceManager.GetString("OAuthRenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To improve security the HSR employs an OAuth authentication principle for it&apos;s mobile services. 
        ///User passwords are therefor never stored in this app.
        ///
        ///A browser window will open a secure connection to the HSR OAuth server. You can log-in with your HSR credentials. After accepting the client permissions you will be redirected back to this app..
        /// </summary>
        public static string OAuthSetup {
            get {
                return ResourceManager.GetString("OAuthSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file: {0}.
        /// </summary>
        public static string OpeningError {
            get {
                return ResourceManager.GetString("OpeningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening file....
        /// </summary>
        public static string OpeningFile {
            get {
                return ResourceManager.GetString("OpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week {0}.
        /// </summary>
        public static string PivotWeek {
            get {
                return ResourceManager.GetString("PivotWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) rubicon IT GmbH, www.rubicon.eu
        ///
        ///See the NOTICE file distributed with this work for additional information
        ///regarding copyright ownership.  rubicon licenses this file to you under 
        ///the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this 
        ///file except in compliance with the License.  You may obtain a copy of the 
        ///License at
        ///
        ///http://www.apache.org/licenses/LICENSE-2.0
        ///
        ///Unless required by applicable law or agreed to in writing, software 
        ///distributed under the License is dis [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Remotion_Linq_License {
            get {
                return ResourceManager.GetString("Remotion_Linq_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSR Account.
        /// </summary>
        public static string SettingAccountTitle {
            get {
                return ResourceManager.GetString("SettingAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration and Usage.
        /// </summary>
        public static string SettingAccountTitleSub {
            get {
                return ResourceManager.GetString("SettingAccountTitleSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Info, Licenses.
        /// </summary>
        public static string SettingAppInfoSubTitle {
            get {
                return ResourceManager.GetString("SettingAppInfoSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Info.
        /// </summary>
        public static string SettingAppInfoTitle {
            get {
                return ResourceManager.GetString("SettingAppInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the cache?.
        /// </summary>
        public static string SettingCacheClearConfirm {
            get {
                return ResourceManager.GetString("SettingCacheClearConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        public static string SettingCacheTitle {
            get {
                return ResourceManager.GetString("SettingCacheTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Files, {1:0.00} MB.
        /// </summary>
        public static string SettingCacheTitleSub {
            get {
                return ResourceManager.GetString("SettingCacheTitleSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official HSR App.
        /// </summary>
        public static string SettingOfficialTitle {
            get {
                return ResourceManager.GetString("SettingOfficialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For assistence please contact the HSR IT-ServiceDesk.
        /// </summary>
        public static string SettingOfficialTitleSub {
            get {
                return ResourceManager.GetString("SettingOfficialTitleSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Management.
        /// </summary>
        public static string SettingStorageTitle {
            get {
                return ResourceManager.GetString("SettingStorageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache, Network Data.
        /// </summary>
        public static string SettingStorageTitleSub {
            get {
                return ResourceManager.GetString("SettingStorageTitleSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache successfully cleared.
        /// </summary>
        public static string SettingSuccessCacheClear {
            get {
                return ResourceManager.GetString("SettingSuccessCacheClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2009-2016 Krueger Systems, Inc.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright no [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sqlite_net_License {
            get {
                return ResourceManager.GetString("sqlite_net_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 							 Apache License
        ///					   Version 2.0, January 2004
        ///					http://www.apache.org/licenses/
        ///
        ///TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///1. Definitions.
        ///
        ///  &quot;License&quot; shall mean the terms and conditions for use, reproduction,
        ///  and distribution as defined by Sections 1 through 9 of this document.
        ///
        ///  &quot;Licensor&quot; shall mean the copyright owner or entity authorized by
        ///  the copyright owner that is granting the License.
        ///
        ///  &quot;Legal Entity&quot; shall mean the union of the acting entity  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SQLitePCL_License {
            get {
                return ResourceManager.GetString("SQLitePCL_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 							 Apache License
        ///					   Version 2.0, January 2004
        ///					http://www.apache.org/licenses/
        ///
        ///TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///1. Definitions.
        ///
        ///  &quot;License&quot; shall mean the terms and conditions for use, reproduction,
        ///  and distribution as defined by Sections 1 through 9 of this document.
        ///
        ///  &quot;Licensor&quot; shall mean the copyright owner or entity authorized by
        ///  the copyright owner that is granting the License.
        ///
        ///  &quot;Legal Entity&quot; shall mean the union of the acting entity  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Square_License {
            get {
                return ResourceManager.GetString("Square_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) Tunnel Vision Laboratories, LLC. All rights reserved.
        ///
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use
        ///these files except in compliance with the License. You may obtain a copy of the
        ///License at
        ///
        ///http://www.apache.org/licenses/LICENSE-2.0
        ///
        ///Unless required by applicable law or agreed to in writing, software distributed
        ///under the License is distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR
        ///CONDITIONS OF ANY KIND, either express or implied. See the Li [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StyleCopAnalyzers_License {
            get {
                return ResourceManager.GetString("StyleCopAnalyzers_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2013, Dominick Baier, Brock Allen
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without modification,
        ///are permitted provided that the following conditions are met:
        ///
        ///  Redistributions of source code must retain the above copyright notice, this
        ///  list of conditions and the following disclaimer.
        ///
        ///  Redistributions in binary form must reproduce the above copyright notice, this
        ///  list of conditions and the following disclaimer in the documentation and/or [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Thinktecture_IdentiyModel_License {
            get {
                return ResourceManager.GetString("Thinktecture_IdentiyModel_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-Party Libraries.
        /// </summary>
        public static string ThirdPartyLibraries {
            get {
                return ResourceManager.GetString("ThirdPartyLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses for third-party libraries..
        /// </summary>
        public static string ThirdPartyLibrariesText {
            get {
                return ResourceManager.GetString("ThirdPartyLibrariesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSR Account.
        /// </summary>
        public static string TileAccount {
            get {
                return ResourceManager.GetString("TileAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADUNIS.
        /// </summary>
        public static string TileADUNIS {
            get {
                return ResourceManager.GetString("TileADUNIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        public static string TileBadge {
            get {
                return ResourceManager.GetString("TileBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus Map.
        /// </summary>
        public static string TileCampusMap {
            get {
                return ResourceManager.GetString("TileCampusMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exams.
        /// </summary>
        public static string TileExams {
            get {
                return ResourceManager.GetString("TileExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture Notes.
        /// </summary>
        public static string TileLectureNotes {
            get {
                return ResourceManager.GetString("TileLectureNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string TileMenu {
            get {
                return ResourceManager.GetString("TileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string TileNews {
            get {
                return ResourceManager.GetString("TileNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Setup.
        /// </summary>
        public static string TileSetupAccount {
            get {
                return ResourceManager.GetString("TileSetupAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSR Sport.
        /// </summary>
        public static string TileSport {
            get {
                return ResourceManager.GetString("TileSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable.
        /// </summary>
        public static string TileTimetable {
            get {
                return ResourceManager.GetString("TileTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating badge saldo....
        /// </summary>
        public static string UpdateBadgeSaldo {
            get {
                return ResourceManager.GetString("UpdateBadgeSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cal-Week: {0} - TW: {1}.
        /// </summary>
        public static string WeekSelect {
            get {
                return ResourceManager.GetString("WeekSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Week.
        /// </summary>
        public static string WeekSelection {
            get {
                return ResourceManager.GetString("WeekSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2017 James Montemagno
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The abo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xam_Plugins_Settings_License {
            get {
                return ResourceManager.GetString("Xam_Plugins_Settings_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation Contributors
        ///
        ///All rights reserved.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xamarin_License {
            get {
                return ResourceManager.GetString("Xamarin_License", resourceCulture);
            }
        }
    }
}
