//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsr.Campus.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Licenses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Licenses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hsr.Campus.Core.Resources.Licenses", typeof(Licenses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _NET_Core_Library_License {
            get {
                return ResourceManager.GetString("_NET_Core_Library_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. Please read them. They apply to the software named above, which includes the media on which you received it, if any. The terms also apply to any Microsoft
        ///
        ///·         updates,
        ///·         supplements,
        ///·          Internet-based services, and
        ///·          support services
        ///
        ///for this software, unless other terms accompany those items. If so, those terms apply.
        ///BY USING THE SOFTWARE, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _NET_Library_License {
            get {
                return ResourceManager.GetString("_NET_Library_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _NET_Standard_Library_License {
            get {
                return ResourceManager.GetString("_NET_Standard_Library_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License
        ///
        ///Copyright (c) 2013 Paul Betts, 2017 Alex Rainman
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModernHttpClient_License {
            get {
                return ResourceManager.GetString("ModernHttpClient_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Public License (MS-PL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you
        ///accept this license. If you do not accept the license, do not use the software.
        ///
        ///1. Definitions
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the
        ///same meaning here as under U.S. copyright law.
        ///A &quot;contribution&quot; is the original software, or any additions or changes to the software.
        ///A &quot;contributor&quot; is any person that distributes its contribution und [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MvvmCross_License {
            get {
                return ResourceManager.GetString("MvvmCross_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2007 James Newton-King
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of
        ///this software and associated documentation files (the &quot;Software&quot;), to deal in
        ///the Software without restriction, including without limitation the rights to
        ///use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
        ///the Software, and to permit persons to whom the Software is furnished to do so,
        ///subject to the following conditions:
        ///
        ///The ab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Newtonsoft_Json_License {
            get {
                return ResourceManager.GetString("Newtonsoft_Json_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) rubicon IT GmbH, www.rubicon.eu
        ///
        ///See the NOTICE file distributed with this work for additional information
        ///regarding copyright ownership.  rubicon licenses this file to you under 
        ///the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this 
        ///file except in compliance with the License.  You may obtain a copy of the 
        ///License at
        ///
        ///http://www.apache.org/licenses/LICENSE-2.0
        ///
        ///Unless required by applicable law or agreed to in writing, software 
        ///distributed under the License is dis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Remotion_Linq_License {
            get {
                return ResourceManager.GetString("Remotion_Linq_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2009-2016 Krueger Systems, Inc.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sqlite_net_License {
            get {
                return ResourceManager.GetString("sqlite_net_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 							 Apache License
        ///					   Version 2.0, January 2004
        ///					http://www.apache.org/licenses/
        ///
        ///TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///1. Definitions.
        ///
        ///  &quot;License&quot; shall mean the terms and conditions for use, reproduction,
        ///  and distribution as defined by Sections 1 through 9 of this document.
        ///
        ///  &quot;Licensor&quot; shall mean the copyright owner or entity authorized by
        ///  the copyright owner that is granting the License.
        ///
        ///  &quot;Legal Entity&quot; shall mean the union of the acting entity  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLitePCL_License {
            get {
                return ResourceManager.GetString("SQLitePCL_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 							 Apache License
        ///					   Version 2.0, January 2004
        ///					http://www.apache.org/licenses/
        ///
        ///TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///1. Definitions.
        ///
        ///  &quot;License&quot; shall mean the terms and conditions for use, reproduction,
        ///  and distribution as defined by Sections 1 through 9 of this document.
        ///
        ///  &quot;Licensor&quot; shall mean the copyright owner or entity authorized by
        ///  the copyright owner that is granting the License.
        ///
        ///  &quot;Legal Entity&quot; shall mean the union of the acting entity  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Square_License {
            get {
                return ResourceManager.GetString("Square_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) Tunnel Vision Laboratories, LLC. All rights reserved.
        ///
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use
        ///these files except in compliance with the License. You may obtain a copy of the
        ///License at
        ///
        ///http://www.apache.org/licenses/LICENSE-2.0
        ///
        ///Unless required by applicable law or agreed to in writing, software distributed
        ///under the License is distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR
        ///CONDITIONS OF ANY KIND, either express or implied. See the Li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StyleCopAnalyzers_License {
            get {
                return ResourceManager.GetString("StyleCopAnalyzers_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2013, Dominick Baier, Brock Allen
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without modification,
        ///are permitted provided that the following conditions are met:
        ///
        ///  Redistributions of source code must retain the above copyright notice, this
        ///  list of conditions and the following disclaimer.
        ///
        ///  Redistributions in binary form must reproduce the above copyright notice, this
        ///  list of conditions and the following disclaimer in the documentation and/or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Thinktecture_IdentiyModel_License {
            get {
                return ResourceManager.GetString("Thinktecture_IdentiyModel_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2017 James Montemagno
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The abo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Xam_Plugins_Settings_License {
            get {
                return ResourceManager.GetString("Xam_Plugins_Settings_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation Contributors
        ///
        ///All rights reserved.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Xamarin_License {
            get {
                return ResourceManager.GetString("Xamarin_License", resourceCulture);
            }
        }
    }
}
